---
- name: make
  become: true
  become_user: domjudge
  command: make judgehost
  args:
    chdir: /home/domjudge/src/domjudge-{{ version }}
    creates: /home/domjudge/domjudge/judgehost/etc

- name: install
  become: true
  command: make install-judgehost
  args:
    chdir: /home/domjudge/src/domjudge-{{ version }}
    creates: /home/domjudge/domjudge/judgehost/lib

- name: create judgehost user
  become: true
  loop: "{{ range(0, judgehosts) | list }}"
  ansible.builtin.user:
    name: domjudge-run-{{ item }}
    create_home: false
    shell: /bin/false
    state: present

- name: domjudge judgehost service
  become: true
  template:
    src: templates/domjudge-judgehost@.service
    dest: /etc/systemd/system/domjudge-judgehost@.service
    mode: 0644

- name: domjudge cgroup service
  become: true
  template:
    src: templates/create-cgroups.service
    dest: /etc/systemd/system/create-cgroups.service
    mode: 0644

- name: check cgroup memory in grub
  become: true
  lineinfile:
    backup: true
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=".*cgroup_enable'
    state: absent
  check_mode: true
  register: cgroup_enable_grub_check
  changed_when: false

- name: enable cgroup memory in grub
  become: true
  when: cgroup_enable_grub_check.found == 0
  notify: update grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: true
    regexp: "^(GRUB_CMDLINE_LINUX_DEFAULT=\".*)\"$"
    line: '\1 cgroup_enable=memory"'

- name: check swapaccount in grub
  become: true
  lineinfile:
    backup: true
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=".*swapaccount'
    state: absent
  check_mode: true
  register: swapaccount_grub_check
  changed_when: false

- name: enable swapaccount in grub
  become: true
  when: swapaccount_grub_check.found == 0
  notify: update grub
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: true
    regexp: "^(GRUB_CMDLINE_LINUX_DEFAULT=\".*)\"$"
    line: '\1 swapaccount=1"'

- name: restart after update-grub
  when: swapaccount_grub_check.found == 0 or cgroup_enable_grub_check == 0
  become: true
  reboot: {}

- name: make chroot
  become: true
  command: bin/dj_make_chroot
  args:
    chdir: /home/domjudge/domjudge/judgehost
    creates: /chroot/domjudge

- name: start and enable cgroup service
  become: true
  service:
    name: create-cgroups
    state: started
    enabled: true

- name: start and enable judgehost service
  become: true
  loop: "{{ range(0, judgehosts) | list }}"
  service:
    name: domjudge-judgehost@{{ item }}
    state: started
    enabled: true

- name: judgehost restapi secret configuration
  become: true
  template:
    src: templates/restapi.secret
    dest: /home/domjudge/domjudge/judgehost/etc/restapi.secret
    mode: 0600
