---
- name: install requirements
  become: true
  apt:
    name:
      - build-essential
      - acl
      - zip
      - unzip
      - mariadb-server
      - python3-mysqldb
      - apache2
      - php
      - php-fpm
      - php-gd
      - php-cli
      - php-intl
      - php-mbstring
      - php-mysql
      - php-curl
      - php-json
      - php-xml
      - php-zip
      - composer
      - ntp
      - libcgroup-dev
      - libcurl4-gnutls-dev
      - libjsoncpp-dev
      - libmagic-dev

- name: starting and enabling the mariadb service
  service:
    name: mariadb
    state: started
    enabled: true

- name: setting up root credentials
  ignore_errors: true
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_user: root
    login_host: "localhost"
    host: localhost
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: true
    state: present

- name: get mysql databases
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    filter: databases
  register: mysql_info

- name: create domjudge user
  ansible.builtin.user:
    name: domjudge
    create_home: true
    state: present

- name: create Downloads directory
  become: true
  become_user: domjudge
  file:
    path: /home/domjudge/src
    mode: 0755
    state: directory

- name: download
  become: true
  become_user: domjudge
  ansible.builtin.unarchive:
    src: https://www.domjudge.org/releases/domjudge-{{ version }}.tar.gz
    dest: /home/domjudge/src
    remote_src: true
    creates: /home/domjudge/src/domjudge-{{ version }}

- name: configure
  become: true
  become_user: domjudge
  command: ./configure --prefix=$HOME/domjudge
  args:
    chdir: /home/domjudge/src/domjudge-{{ version }}
    creates: paths.mk

- name: make
  become: true
  become_user: domjudge
  command: make domserver
  when: domserver == "enabled"
  args:
    chdir: /home/domjudge/src/domjudge-{{ version }}

- name: install
  become: true
  command: make install-domserver
  when: domserver == "enabled"
  args:
    chdir: /home/domjudge/src/domjudge-{{ version }}

- name: generate database password
  become: true
  command: bin/dj_setup_database genpass
  when: domserver == "enabled" and "domjudge" not in mysql_info.databases
  args:
    chdir: /home/domjudge/domjudge/domserver

- name: setup database
  become: true
  command: bin/dj_setup_database -u root -p {{ mysql_root_password }} install
  when: domserver == "enabled" and "domjudge" not in mysql_info.databases
  args:
    chdir: /home/domjudge/domjudge/domserver

- name: apache configuration softlink
  become: true
  when: domserver == "enabled"
  file:
    src: /home/domjudge/domjudge/domserver/etc/apache.conf
    dest: /etc/apache2/conf-available/domjudge.conf
    state: link

- name: phpfpm configuration softlink
  become: true
  when: domserver == "enabled"
  file:
    src: /home/domjudge/domjudge/domserver/etc/domjudge-fpm.conf
    dest: /etc/php/{{ php_version }}/fpm/pool.d/domjudge.conf
    state: link

- name: enable apache modes
  become: true
  when: domserver == "enabled"
  command: a2enmod proxy_fcgi setenvif rewrite

- name: enable apache configs
  become: true
  when: domserver == "enabled"
  command: a2enconf php{{ php_version }}-fpm domjudge

- name: reload apache
  when: domserver == "enabled"
  service:
    name: apache2
    state: reloaded

- name: reload php-fpm
  when: domserver == "enabled"
  service:
    name: php{{ php_version }}-fpm
    state: reloaded
