---
- name: reload nginx
  become: true
  service:
    name: nginx
    state: reloaded

- name: reload php-fpm
  become: true
  service:
    name: php{{ php_version }}-fpm
    state: reloaded

- name: update grub
  become: true
  command: update-grub

- name: reboot
  become: true
  reboot: {}
